name = "misteln/aiken"
version = "0.0.0"
compiler = "v1.1.1"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'misteln/aiken'"

[repository]
user = "misteln"
project = "aiken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
